<a href="https://colab.research.google.com/github/ROOPESH9462/ml-ass/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
add = arr1 + arr2
print("Addition :", add)
sub = arr1 - arr2
print("Subtraction :", sub)
mul = arr1 * arr2
print("Multiplication :", mul)
div = arr1 / arr2
print("Division :", div)

Addition : [5 7 9]
Subtraction : [-3 -3 -3]
Multiplication : [ 4 10 18]
Division : [0.25 0.4  0.5 ]


In [5]:
a = np.array([10, 20, 30, 40, 50])
mean = np.mean(a)
std = np.std(a)
print("Mean of the array:", mean)
print("Standard Deviation of the array:", std)

Mean of the array: 30.0
Standard Deviation of the array: 14.142135623730951


In [6]:
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [7]:
b=np.array([1,2,3,4,5,6,7,8])
reshape_arr=b.reshape(2,4)
print(reshape_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=c[1:,:2]
print(c)
print()
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[4 5]
 [7 8]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
multiplication = a * b
division = a / b
print("Addition: ", addition)
print("Multiplication: ", multiplication)
print("Division: ", division)

Addition:  [5 7 9]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


In [9]:
arr = np.random.rand(4, 4)
meancol = np.mean(arr, axis=0)
maxval = np.max(arr)
sumele = np.sum(arr)
print("Random Array:\n", arr)
print("Mean of each column: ", meancol)
print("Maximum value of the entire array: ", maxval)
print("Sum of all elements: ", sumele)

Random Array:
 [[0.98733087 0.34280723 0.19421374 0.59782006]
 [0.44267012 0.12520075 0.36364118 0.25897   ]
 [0.54879546 0.98087369 0.47465686 0.14582387]
 [0.19326521 0.17685126 0.72759816 0.00680085]]
Mean of each column:  [0.54301542 0.40643323 0.44002748 0.25235369]
Maximum value of the entire array:  0.9873308742911745
Sum of all elements:  6.5673193077740075


In [10]:
arr2=np.array([1,2,3,4])
result=(arr2+10)*2
print(result)

[22 24 26 28]


In [11]:
import numpy as np
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original Array:\n", arr)
seclay = arr[1]
print("\nSecond Layer:\n", seclay)
extracted_rows_columns = arr[:, :2, -3:]
print("\nFirst two rows and last three columns from each layer:\n", extracted_rows_columns)
arr[arr % 3 == 0] = -1
print("\nArray after replacing elements divisible by 3 with -1:\n", arr)

Original Array:
 [[[93 18 50 39 37]
  [51 75  4 57 25]
  [19 30 16 47 58]
  [29 26 85 71 77]]

 [[17 75 14 24 17]
  [23 57 42 85 97]
  [59 85 56 37 92]
  [37 82 65 82 95]]

 [[47 55 49 13 81]
  [36 66 35 93 62]
  [39 31 99 81 61]
  [76 89 33 24 40]]]

Second Layer:
 [[17 75 14 24 17]
 [23 57 42 85 97]
 [59 85 56 37 92]
 [37 82 65 82 95]]

First two rows and last three columns from each layer:
 [[[50 39 37]
  [ 4 57 25]]

 [[14 24 17]
  [42 85 97]]

 [[49 13 81]
  [35 93 62]]]

Array after replacing elements divisible by 3 with -1:
 [[[-1 -1 50 -1 37]
  [-1 -1  4 -1 25]
  [19 -1 16 47 58]
  [29 26 85 71 77]]

 [[17 -1 14 -1 17]
  [23 -1 -1 85 97]
  [59 85 56 37 92]
  [37 82 65 82 95]]

 [[47 55 49 13 -1]
  [-1 -1 35 -1 62]
  [-1 31 -1 -1 61]
  [76 89 -1 -1 40]]]


In [15]:
arr = np.random.randint(1, 21, size=(3, 3))
print("Original Array:\n", arr)
row_means = arr.mean(axis=1, keepdims=True)
normalized_arr = arr - row_means
print("\nRow-wise Normalized Array:\n", normalized_arr)
squared_arr = arr ** 2
print("\nSquared Array:\n", squared_arr)
top_3_indices = np.unravel_index(np.argsort(arr, axis=None)[-3:], arr.shape)
print("\nIndices of the top 3 maximum values:", top_3_indices)
print("Top 3 maximum values:", arr[top_3_indices])

Original Array:
 [[19 20 16]
 [18  5 18]
 [11  5 12]]

Row-wise Normalized Array:
 [[ 0.66666667  1.66666667 -2.33333333]
 [ 4.33333333 -8.66666667  4.33333333]
 [ 1.66666667 -4.33333333  2.66666667]]

Squared Array:
 [[361 400 256]
 [324  25 324]
 [121  25 144]]

Indices of the top 3 maximum values: (array([1, 0, 0]), array([2, 0, 1]))
Top 3 maximum values: [18 19 20]
